name: CI
run-name: "Hello ${{ github.event.client_payload.run_name_detail }} World"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  coso:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /rate_limit

  # call-1:
  #   uses: ./.github/workflows/reusable.yaml

  # call-2:
  #   uses: ./.github/workflows/reusable.yaml
  #   with:
  #     MY_BOOLEAN: true

  # call-3:
  #   uses: ./.github/workflows/reusable.yaml
  #   with:
  #     MY_BOOLEAN: false
