name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        input1: [true, false]
        input2: [true, false]
    uses: ./.github/workflows/reusable.yaml
    with:
      INPUT_1: ${{ matrix.input1 }}
      INPUT_2: ${{ matrix.input2 }}
