name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Expose URL
        uses: actions/github-script@v7
        with:
          script: |
            core.info(JSON.stringify(github))
