name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        publish: [true, false]
    uses: ./.github/workflows/reusable.yaml
    with:
      PUBLISH_ARTIFACT: ${{ matrix.publish }}
