name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  example-1:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: date

  example-2:
    runs-on: ubuntu-latest
    steps:
      - run: date

  pr-ready:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - example-1
      - example-2
    steps:
      - name: Emit overall result of workflow
        uses: actions/github-script@v7
        with:
          script: |
            const results = ${{ toJSON(needs.*.result) }}
            if (!results.every(result => result == 'success' || result == 'skipped')) {
              core.setFailed('Failed mandatory checks found')
            }