name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Expose URL
        uses: actions/github-script@v7
        env:
          URL: 'https://github.com/${{ github.repository_owner}}/hello/actions/runs/123'
        with:
          script: 'core.notice(`Triggered job: ${process.env.URL`)'