name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Secrets
        id: generate-secrets
        run: |
          echo "key=SONAR_TOKEN" | tee -a $GITHUB_OUTPUT
          echo "value=secreto2" | tee -a $GITHUB_OUTPUT

      - name: Display
        run: |
          echo ${SONAR_TOKEN}
          echo ${SONARQUBE_TOKEN}
        env:
          SONAR_TOKEN: ${{ steps.generate-secrets.outputs.key }}
          SONARQUBE_TOKEN: ${{steps.generate-secrets.outputs.value }}
