name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  call-1:
    uses: ./.github/workflows/reusable.yaml

  call-2:
    uses: ./.github/workflows/reusable.yaml
    with:
      MY_BOOLEAN: true

  call-3:
    uses: ./.github/workflows/reusable.yaml
    with:
      MY_BOOLEAN: false