name: CI
run-name: "Publish ${{ github.event_name == 'workflow_dispatch' && 'Alpha' || '' }} Helm Charts"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  coso:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello

  # call-1:
  #   uses: ./.github/workflows/reusable.yaml

  # call-2:
  #   uses: ./.github/workflows/reusable.yaml
  #   with:
  #     MY_BOOLEAN: true

  # call-3:
  #   uses: ./.github/workflows/reusable.yaml
  #   with:
  #     MY_BOOLEAN: false