on:
  workflow_call:
jobs:
  send-deploy-events:
    strategy:
      matrix:
        difference: [1, 2]

    runs-on: ubuntu-latest
    steps:
      - name: Prepare Jira Comment
        id: prepare-jira
        uses: actions/github-script@v6
        env:
          REPOSITORY: ${{ github.repository }}
          SHA: ${{ github.sha }}
        with:
          debug: true
          script: |
            const { REPOSITORY, SHA } = process.env

            // Unpack owner, repo and commit
            const [owner, repo] = REPOSITORY.split('/')

            // Retrieve Run URL

            // https://api.github.com/repos/hello/actions/runs/6712384947/jobs
            // try {
              const {data: response}  = await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/jobs', {
                owner,
                repo,
                run_id: context.runId,
              })
              core.info(context.job)
              core.info(JSON.stringify(response,null,2))
              // const jobRun = reponse.jobs.filter((job) => job.id == context.job).pop()
              // const jobRunUrl = jobRun.html_url
              // core.warning(jobRunUrl)
            // } catch (err) {
              // core.warning(`Unable retrieve a workflow run with run ID: ${context.runId}`)
              // return
            // }