on:
  workflow_call:
    inputs:
      INPUT_1:
        description:
        type: boolean
        required: false
        default: false
      INPUT_2:
        description:
        type: boolean
        required: false
        default: false
jobs:
    build:
      strategy:
        matrix:
          result: ['true', 'false']

      runs-on: ubuntu-latest
      steps:
        - name: Generate Outputs
          id: generate
          run: echo "my-var=${{ matrix.result }}" | tee -a "${GITHUB_OUTPUT}"
        - run: echo "my-var=${{ steps.generate.outputs.my-var }} INPUT_1=${{ inputs.INPUT_1 }} INPUT_2=${{ inputs.INPUT_2 }}"
        - name: Build
          if: (inputs.INPUT_1 || inputs.INPUT_2) && steps.generate.outputs.my-var != 'true'
          run: date
        - name: Publish
          if: inputs.INPUT_1 && steps.generate.outputs.my-var != 'true'
          run: date
